---
title: name of api
description: very very long description
mocks:
  - summary: get patients
    description: get patients
    request:
      method: GET
      path: /patients
      queryParameters:
        key: value
      headers:
        content: helllo
      cookies:
        content: helllo
      body: content in body
    response:
      statusCode: 200
      headers:
        content: helllo
      cookies:
        content: helllo
      body: content in body
  - summary: post a patient
    description: post a patient
    request:
      method: POST
      path: /patients
      body: {
  "firstName": "firname",
  "lastnema": "lastname"
}
    response:
      statusCode: 200
      headers:
        content: helllo
      cookies:
        content: helllo
      body: {
  "id": "12",
  "firstName": "firname",
  "lastnema": "lastname"
}
